### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by LWShowTime** [naver-ai/dual-teacher#1]
Congratulations to you and thansk for your work. I wonder when will the code be released?

**Comment by dyhan0920** [comment]
Hello @LWShowTime

Our code is in its final internal review stage. 
Sorry for the delay and ask that you stay tuned for the upcoming release.

**Comment by NaJaeMin92** [comment]
Hello @LWShowTime 

Our code has just been released.
Thank you for your patience.
