### ISSUE TITLE
Question about the switched teacher model

### ISSUE THREAD

**Issue by Hugo-cell111** [naver-ai/dual-teacher#2]
Hi! About the detail of your work, in my understanding, in the 1st epoch, the student model is trained by the teacher model A. and at the end of the 1st epoch, A is EMAed by the student model; in the 2nd epoch, the student model is trained by the teacher model B. and at the end of the 1st epoch, B is EMAed by the student model; in the 3rd epoch, it is totally the same as that in the 1st epoch. Am I right?

**Comment by NaJaeMin92** [comment]
Hello @Hugo-cell111 

Thank you for your interest in our research.

Yes, the same teacher contributes to both the 1st and 3rd epochs.

**Comment by Hugo-cell111** [comment]
OK, I get it. Thank you so much!
